# Generated by Django 6.0.6 on 2026-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0002_alter_course_workspace_id'),
        ('enrollments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollmentattempt',
            name='cf_enrollment_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='enrollmentattempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], db_index=True, max_length=20),
        ),
        migrations.AddIndex(
            model_name='enrollmentattempt',
            index=models.Index(fields=['created_at'], name='enrollments_created_74a58f_idx'),
        ),
    ]
