# Generated by Django 6.0.7 on 2026-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollments', '0002_alter_enrollmentattempt_cf_enrollment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollmentattempt',
            name='cf_suspended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enrollmentattempt',
            name='cf_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollmentattempt',
            name='cf_suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
