# Generated by Django 6.0.6 on 2026-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='workspace_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
