# Generated by Django 6.0.5 on 2026-09-14 12:08

import apps.courses.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_workspace_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckoutOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField(blank=True)),
                ('language', models.CharField(choices=[('en', 'English'), ('fr', 'French')], default='en', max_length=2)),
                ('mockup_image', models.CharField(max_length=1000, validators=[apps.courses.models.validate_mockup_image])),
                ('mockup_alt', models.CharField(max_length=255)),
                ('highlights', models.TextField(blank=True, help_text='Short facts, one per line (e.g. No prior knowledge required).')),
                ('closing_note', models.TextField(blank=True)),
                ('course', models.OneToOneField(blank=True, help_text='Attach this offer to its course. Leave blank to keep it as an unpublished draft.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_offer', to='courses.course')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CheckoutBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_bonus', models.BooleanField(default=False)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='courses.checkoutoffer')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
