# Generated by Django 6.1.1 on 2026-09-25 19:33

import apps.courses.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_course_slug_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkoutoffer',
            name='image',
            field=models.ImageField(blank=True, upload_to='offers/'),
        ),
        migrations.AlterField(
            model_name='checkoutoffer',
            name='mockup_alt',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='checkoutoffer',
            name='mockup_image',
            field=models.CharField(blank=True, max_length=1000, validators=[apps.courses.models.validate_mockup_image]),
        ),
    ]
