# Generated by Django 6.0.6 on 2026-06-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickFunnelsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A descriptive name for this configuration.', max_length=255)),
                ('is_active', models.BooleanField(default=False, help_text='Set to true if this is the active configuration.')),
                ('client_key', models.TextField(blank=True)),
                ('client_secret', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], default='PENDING', max_length=20)),
                ('workspace_id', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace_name', models.CharField(blank=True, max_length=255, null=True)),
                ('team_id', models.CharField(blank=True, max_length=255, null=True)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
                ('business_info', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'ClickFunnels Configuration',
                'verbose_name_plural': 'ClickFunnels Configurations',
            },
        ),
    ]
