# Generated by Django 6.0.6 on 2026-06-03 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clickfunnelsconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Set to true if this is the active configuration.'),
        ),
        migrations.AlterField(
            model_name='clickfunnelsconfig',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='clickfunnelsconfig',
            name='workspace_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
