# Generated by Django 6.0.6 on 2026-06-03 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0002_alter_clickfunnelsconfig_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clickfunnelsconfig',
            old_name='client_key',
            new_name='api_access_token',
        ),
        migrations.RemoveField(
            model_name='clickfunnelsconfig',
            name='client_secret',
        ),
        migrations.AddField(
            model_name='clickfunnelsconfig',
            name='api_user_agent',
            field=models.CharField(default='ValuedCRM/1.0', help_text='Mandatory User-Agent identification for CFv2.', max_length=255),
        ),
    ]
