# Generated by Django 6.0.6 on 2026-06-04 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0003_rename_client_key_clickfunnelsconfig_api_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clickfunnelsconfig',
            name='workspace_subdomain',
            field=models.CharField(blank=True, help_text='The subdomain for workspace-level API calls.', max_length=255, null=True),
        ),
    ]
