# Generated by Django 6.1.1 on 2026-09-25 21:35

from django.db import migrations, models


def create_default_settings(apps, schema_editor):
    NotificationSettings = apps.get_model("configuration", "NotificationSettings")
    if not NotificationSettings.objects.exists():
        NotificationSettings.objects.create(alert_email="contact@digital-mind.tech", alerts_enabled=True)


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0004_clickfunnelsconfig_workspace_subdomain'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alert_email', models.EmailField(blank=True, help_text='Adresse qui reçoit les alertes « À traiter ». Laisser vide pour ne rien envoyer.', max_length=254)),
                ('alerts_enabled', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StaffAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=100, unique=True)),
                ('summary', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_settings, migrations.RunPython.noop),
    ]
