# Generated by Django 6.0.6 on 2026-07-07 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event_type', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('PRODUCT_MATCHED', 'Product Matched'), ('CUSTOMER_MATCHED', 'Customer Matched'), ('MATCHED', 'Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('REMATCHED', 'Rematched'), ('IGNORED', 'Ignored'), ('PROVISIONING_REQUESTED', 'Provisioning Requested'), ('PROVISIONING_COMPLETED', 'Provisioning Completed'), ('PROVISIONING_FAILED', 'Provisioning Failed')], max_length=50)),
                ('detail', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField()),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('transactions_seen', models.IntegerField(default=0)),
                ('new_payments', models.IntegerField(default=0)),
                ('errors', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='TaraConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='A descriptive name for this configuration.', max_length=255)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Set to true if this is the active configuration.')),
                ('api_key', models.TextField(blank=True)),
                ('webhook_secret', models.TextField(blank=True)),
                ('validation_status', models.CharField(choices=[('PENDING', 'Pending'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Tara Configuration',
                'verbose_name_plural': 'Tara Configurations',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='tara', max_length=50)),
                ('provider_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('product_ref', models.CharField(blank=True, db_index=True, max_length=255)),
                ('extracted_phone', models.CharField(blank=True, max_length=50)),
                ('extracted_email', models.EmailField(blank=True, max_length=254)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('VERIFIED', 'Verified'), ('MATCHED', 'Matched'), ('NEEDS_REVIEW', 'Needs Review'), ('DUPLICATE', 'Duplicate'), ('IGNORED', 'Ignored')], db_index=True, default='RECEIVED', max_length=20)),
                ('match_confidence', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('NONE', 'None')], default='NONE', max_length=10)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, help_text='Operator notes explaining a manual match/dismissal decision.')),
                ('matched_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tara_payments', to='contacts.contact')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
