# Generated by Django 6.0.5 on 2026-07-30 21:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_workspace_id'),
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(help_text='Stable internal identifier (e.g. for future checkout/order references). Not shown to customers.', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Administrator-facing and customer-facing display name.', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('currency', models.CharField(choices=[('XAF', 'XAF — Central Africa CFA Franc'), ('XOF', 'XOF — West Africa CFA Franc')], default='XAF', max_length=3)),
                ('installment_count', models.PositiveIntegerField(default=1, help_text='Number of installments. Use 1 for a single one-time payment.', validators=[django.core.validators.MinValueValidator(1)])),
                ('installment_amount', models.DecimalField(decimal_places=2, help_text='Amount per installment, in the currency above. The total is computed, not entered directly.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('installment_interval_days', models.PositiveIntegerField(default=30, help_text='Days between installments after the first. Ignored when installment_count is 1.')),
                ('access_policy', models.CharField(choices=[('FIRST_INSTALLMENT', 'After first verified installment'), ('FULL_PAYMENT', 'After full payment')], default='FULL_PAYMENT', help_text='When course access becomes eligible. Never inferred from name, price, or installment count.', max_length=30)),
                ('is_active', models.BooleanField(db_index=True, default=False, help_text='Published/purchasable by checkout. Unlike Tara/ClickFunnels configuration, multiple plans may be active at once.')),
                ('display_order', models.PositiveIntegerField(db_index=True, default=0)),
                ('course', models.ForeignKey(help_text='The course this plan grants access to. Selected from the existing course catalog only.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_plans', to='courses.course')),
            ],
            options={
                'verbose_name': 'Payment Plan',
                'verbose_name_plural': 'Payment Plans',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
