# Generated by Django 6.0.5 on 2026-07-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_paymentplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='taraconfig',
            name='business_id',
            field=models.CharField(default='', help_text='Tara businessId. Sent openly (not encrypted) in every Tara API call — not a credential, per docs/Tara_API_Reference_Technique.docx.', max_length=255),
        ),
        migrations.AlterField(
            model_name='taraconfig',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, help_text='Enabled/active configuration. Only one configuration may be active at a time.'),
        ),
        migrations.AlterField(
            model_name='taraconfig',
            name='raw_payload',
            field=models.JSONField(blank=True, default=dict, help_text='Unused pending a confirmed safe verification endpoint.'),
        ),
        migrations.AlterField(
            model_name='taraconfig',
            name='validation_status',
            field=models.CharField(choices=[('PENDING', 'Pending (unverified — no safe Tara check confirmed yet)'), ('VALID', 'Valid'), ('INVALID', 'Invalid')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='taraconfig',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='unique_active_tara_config'),
        ),
    ]
