# Generated by Django 6.0.5 on 2026-07-31 07:02

import apps.payments.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0002_alter_course_workspace_id'),
        ('payments', '0005_encrypt_legacy_tara_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Opaque public identifier — safe to use in URLs/return pages. The numeric pk is not.', unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended')], db_index=True, default='PENDING', max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, help_text='Caller-provided checkout idempotency key — a repeated call with this key returns the same Order.', max_length=255, unique=True)),
                ('plan_code', models.CharField(max_length=100)),
                ('plan_name', models.CharField(max_length=255)),
                ('course_cf_id', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('currency', models.CharField(max_length=3)),
                ('installment_count', models.PositiveIntegerField()),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('installment_interval_days', models.PositiveIntegerField()),
                ('total_expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('access_policy', models.CharField(choices=[('FIRST_INSTALLMENT', 'After first verified installment'), ('FULL_PAYMENT', 'After full payment')], max_length=30)),
                ('course', models.ForeignKey(help_text="Set once at creation from the plan's course at that moment. Never reassigned afterward, even if the plan's course later changes.", on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='courses.course')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='contacts.contact')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='payments.paymentplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence', models.PositiveIntegerField(help_text="1-based position within the order's installment schedule.")),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('DUE', 'Due'), ('PENDING', 'Pending'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('WAIVED', 'Waived'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=20)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installments', to='payments.order')),
            ],
            options={
                'ordering': ['order', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tara_product_id', models.CharField(default=apps.payments.models.generate_tara_product_id, max_length=255, unique=True)),
                ('tara_payment_id', models.CharField(blank=True, help_text="Tara's own payment identifier, once known. NULL until the provider assigns one; unique when set (Postgres unique indexes permit multiple NULLs, so this doesn't block multiple not-yet-known attempts).", max_length=255, null=True, unique=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('LINK_CREATED', 'Link Created'), ('PENDING', 'Pending'), ('SUCCEEDED', 'Succeeded'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired'), ('UNKNOWN', 'Unknown')], db_index=True, default='CREATED', max_length=20)),
                ('raw_provider_status', models.CharField(blank=True, help_text="Tara's raw status string, stored uninterpreted — never itself used for business decisions; status above is.", max_length=50)),
                ('provider_message', models.CharField(blank=True, max_length=500)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('telegram_link', models.URLField(blank=True)),
                ('dikalo_link', models.URLField(blank=True)),
                ('general_link', models.URLField(blank=True)),
                ('card_link', models.URLField(blank=True)),
                ('sms_link', models.CharField(blank=True, help_text="An sms: URI, not an http(s) URL per Tara's documented response — plain CharField, since URLField only validates http(s)/ftp schemes.", max_length=500)),
                ('initiated_at', models.DateTimeField(blank=True, help_text='When a payment link was actually created (status -> LINK_CREATED).', null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When a terminal status (SUCCEEDED/FAILED/EXPIRED) was reached.', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Link expiry, once Tara documents/returns one. Unknown/unpopulated in Phase 3.', null=True)),
                ('installment', models.ForeignKey(help_text='PROTECTed, not CASCADEd — a payment attempt is provider-interaction history and must never be silently deleted.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='payments.installment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('total_expected_amount__gt', 0)), name='order_total_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('installment_count__gte', 1)), name='order_installment_count_positive'),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE', 'PAST_DUE', 'COMPLETED', 'CANCELLED', 'SUSPENDED'])), name='order_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.UniqueConstraint(fields=('order', 'sequence'), name='unique_installment_sequence_per_order'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('sequence__gt', 0)), name='installment_sequence_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gt', 0)), name='installment_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='installment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['SCHEDULED', 'DUE', 'PENDING', 'PAID', 'FAILED', 'WAIVED', 'CANCELLED'])), name='installment_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('expected_amount__gt', 0)), name='payment_attempt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['CREATED', 'LINK_CREATED', 'PENDING', 'SUCCEEDED', 'FAILED', 'EXPIRED', 'UNKNOWN'])), name='payment_attempt_status_valid'),
        ),
    ]
