# Generated by Django 6.0.5 on 2026-07-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_order_installment_paymentattempt_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['CREATED', 'LINK_CREATED', 'PENDING', 'SUCCEEDED', 'UNKNOWN'])), fields=('installment',), name='one_active_payment_attempt_per_installment'),
        ),
    ]
