# Generated by Django 6.0.5 on 2026-07-31 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentattempt_one_active_payment_attempt_per_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaraWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_status', models.CharField(choices=[('RECEIVED', 'Received'), ('PROCESSED', 'Processed'), ('UNCORRELATED', 'Uncorrelated'), ('REJECTED', 'Rejected'), ('FAILED', 'Failed')], db_index=True, default='RECEIVED', max_length=20)),
                ('verification_mode', models.CharField(choices=[('UNVERIFIED_TRIGGER', 'Unverified — used only as a trigger'), ('SERVER_TO_SERVER', 'Server-to-server status verified')], default='UNVERIFIED_TRIGGER', max_length=30)),
                ('verification_result', models.CharField(choices=[('PENDING', 'Pending'), ('SUCCESS', 'Success'), ('FAILURE', 'Failure'), ('UNKNOWN', 'Unknown'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=10)),
                ('failure_category', models.CharField(blank=True, choices=[('', '—'), ('BUSINESS_ID_MISMATCH', 'businessId mismatch'), ('UNKNOWN_PRODUCT_ID', 'Unknown productId'), ('UNCORRELATED', 'No safe correlation available'), ('AMOUNT_MISMATCH', 'Webhook amount does not match the expected installment amount'), ('PAYMENT_ID_CONFLICT', 'Tara paymentId already linked to a different attempt'), ('PROVIDER_LOOKUP_INDETERMINATE', 'Server-to-server status lookup was indeterminate'), ('MALFORMED', 'Malformed or inconsistent provider response')], default='', max_length=40)),
                ('business_id', models.CharField(blank=True, max_length=255)),
                ('tara_product_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('tara_payment_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('raw_provider_status', models.CharField(blank=True, help_text="Tara's raw status string as received, uninterpreted.", max_length=50)),
                ('provider_creation_date', models.DateTimeField(blank=True, null=True)),
                ('provider_change_date', models.DateTimeField(blank=True, null=True)),
                ('payload_digest', models.CharField(db_index=True, help_text='SHA-256 hex digest of the raw request body. The body itself is never stored.', max_length=64)),
                ('dedup_key', models.CharField(db_index=True, help_text='SHA-256 hex digest of paymentId|productId|status|changeDate|payload_digest — deterministic deduplication.', max_length=64, unique=True)),
                ('processing_attempts', models.PositiveIntegerField(default=0)),
                ('payment_attempt', models.ForeignKey(blank=True, help_text='Set only via an exact tara_product_id match. Never set from phoneNumber/amount/collectionId.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ['-received_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('processing_status__in', ['RECEIVED', 'PROCESSED', 'UNCORRELATED', 'REJECTED', 'FAILED'])), name='webhook_event_processing_status_valid')],
            },
        ),
    ]
