# Generated by Django 6.0.5 on 2026-07-31 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('payments', '0008_tarawebhookevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('notification_type', models.CharField(choices=[('PAYMENT_CONFIRMATION', 'Payment confirmation')], default='PAYMENT_CONFIRMATION', max_length=30)),
                ('channel', models.CharField(choices=[('EMAIL', 'Email')], default='EMAIL', max_length=10)),
                ('recipient_snapshot', models.CharField(blank=True, help_text='Recipient address frozen at creation time — never re-read from the live Contact at send time.', max_length=255)),
                ('idempotency_key', models.CharField(db_index=True, help_text='SHA-256 hex of notification_type|payment_attempt_id|channel|recipient — never a mutable provider message.', max_length=64, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENDING', 'Sending'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review')], db_index=True, default='PENDING', max_length=20)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_category', models.CharField(blank=True, choices=[('', '—'), ('INVALID_RECIPIENT', 'Missing or invalid recipient address'), ('TRANSIENT_DELIVERY_ERROR', 'Transient delivery error'), ('CONFIGURATION_ERROR', 'Delivery configuration error'), ('MAX_ATTEMPTS_EXCEEDED', 'Maximum delivery attempts exceeded')], default='', max_length=40)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to='contacts.contact')),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to='payments.installment')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to='payments.order')),
                ('payment_attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_confirmations', to='payments.paymentattempt')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='payments_pa_status_39278f_idx')],
            },
        ),
    ]
