# Generated by Django 6.0.5 on 2026-07-31 15:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_paymentconfirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installment',
            options={'ordering': ['order', 'sequence'], 'permissions': [('cancel_installment', 'Can cancel an eligible unpaid installment (Phase 8 administrative action)'), ('waive_installment', 'Can waive an eligible unpaid installment (Phase 8 administrative action)')]},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('cancel_order', 'Can cancel an order (Phase 8 administrative action)'), ('apply_manual_disposition', 'Can apply a manual business disposition to an order')]},
        ),
        migrations.AlterModelOptions(
            name='paymentattempt',
            options={'ordering': ['-created_at'], 'permissions': [('check_tara_status', 'Can trigger a server-to-server Tara status check for a payment attempt')]},
        ),
        migrations.AlterModelOptions(
            name='paymentconfirmation',
            options={'ordering': ['-created_at'], 'permissions': [('retry_payment_confirmation', 'Can retry a FAILED or MANUAL_REVIEW payment confirmation')]},
        ),
        migrations.AddField(
            model_name='order',
            name='manual_disposition',
            field=models.CharField(choices=[('NONE', '—'), ('NEEDS_REVIEW', 'Needs Review'), ('APPROVED_FOR_RETRY', 'Approved for Retry'), ('DENIED_BY_ADMIN', 'Denied by Admin'), ('CUSTOMER_CANCELLED', 'Customer Cancelled'), ('DISPUTED', 'Disputed')], db_index=True, default='NONE', help_text='Administrator business annotation only — never read by any state-transition or eligibility rule.', max_length=30),
        ),
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('administrator_username', models.CharField(blank=True, max_length=150)),
                ('action_type', models.CharField(choices=[('CHECK_TARA_STATUS', 'Check Tara Status'), ('RETRY_CONFIRMATION', 'Retry Confirmation'), ('RETRY_PROVISIONING', 'Retry Provisioning'), ('CANCEL_ORDER', 'Cancel Order'), ('CANCEL_INSTALLMENT', 'Cancel Installment'), ('WAIVE_INSTALLMENT', 'Waive Installment'), ('APPLY_MANUAL_DISPOSITION', 'Apply Manual Disposition')], db_index=True, max_length=40)),
                ('target_type', models.CharField(choices=[('ORDER', 'Order'), ('INSTALLMENT', 'Installment'), ('PAYMENT_ATTEMPT', 'PaymentAttempt'), ('PAYMENT_CONFIRMATION', 'PaymentConfirmation'), ('PROVISIONING_REQUEST', 'ProvisioningRequest')], db_index=True, max_length=30)),
                ('target_reference', models.CharField(help_text='Safe opaque reference to the target (e.g. Order.reference) — never a bare internal pk where a safer identifier exists.', max_length=255)),
                ('previous_state', models.CharField(blank=True, max_length=255)),
                ('resulting_state', models.CharField(blank=True, max_length=255)),
                ('reason', models.TextField(help_text='Mandatory administrator-supplied reason for this action.')),
                ('outcome_category', models.CharField(choices=[('SUCCESS', 'Success'), ('NO_OP_ALREADY_IN_STATE', 'No-op — already in target state'), ('REJECTED_INVALID_STATE', 'Rejected — invalid state for this action'), ('REJECTED_PERMISSION', 'Rejected — insufficient permission'), ('PROVIDER_NON_FINAL', 'Provider result non-final (pending/unknown/timeout/error)'), ('FAILED', 'Failed')], db_index=True, max_length=40)),
                ('request_metadata', models.JSONField(blank=True, default=dict, help_text='Safe metadata only (e.g. remote_addr) — never headers, cookies, or tokens.')),
                ('administrator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('installment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='payments.installment')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='payments.order')),
                ('payment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_audit_logs', to='payments.paymentattempt')),
            ],
            options={
                'verbose_name': 'Admin Audit Log',
                'verbose_name_plural': 'Admin Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
