# Generated by Django 6.0.5 on 2026-08-01 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0010_alter_installment_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentattempt',
            name='next_reconciliation_check_at',
            field=models.DateTimeField(blank=True, help_text='Backoff — not re-selected for verification before this time.', null=True),
        ),
        migrations.AddField(
            model_name='paymentattempt',
            name='reconciliation_check_count',
            field=models.PositiveIntegerField(default=0, help_text='How many times run_hourly_reconciliation has verified this attempt via check_transaction_status().'),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='attempts_examined',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='confirmation_jobs_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='confirmation_jobs_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='confirmation_jobs_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='missing_work_repaired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='provisioning_jobs_completed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='provisioning_jobs_failed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='provisioning_jobs_processed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='run_status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('SUCCESS', 'Success'), ('PARTIAL_FAILURE', 'Partial Failure'), ('FAILED', 'Failed'), ('SKIPPED_OVERLAPPING', 'Skipped (overlapping run)')], db_index=True, default='RUNNING', max_length=30),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='safe_error_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='status_checks',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='still_pending_or_unknown',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='uncorrelated_transaction_list_records',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='verified_failures',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='verified_successes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
