# Generated by Django 6.0.7 on 2026-08-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0011_paymentattempt_next_reconciliation_check_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_pa_status_343680_idx',
        ),
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='errors',
        ),
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='new_payments',
        ),
        migrations.RemoveField(
            model_name='reconciliationrun',
            name='transactions_seen',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='matched_contact',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='matched_product',
        ),
        migrations.DeleteModel(
            name='PaymentTimelineEvent',
        ),
    ]
