# Generated by Django 6.0.7 on 2026-08-04 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0012_remove_payment_payments_pa_status_343680_idx_and_more'),
        ('provisioning', '0004_remove_product_courses_remove_productmapping_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
