# Generated by Django 6.0.7 on 2026-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0013_delete_payment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at'], 'permissions': [('cancel_order', 'Can cancel an order (Phase 8 administrative action)'), ('apply_manual_disposition', 'Can apply a manual business disposition to an order'), ('freeze_enrollment', "Can freeze (suspend) a customer's ClickFunnels course enrollment"), ('resume_enrollment', 'Can resume a previously frozen ClickFunnels course enrollment')]},
        ),
        migrations.AlterField(
            model_name='adminauditlog',
            name='action_type',
            field=models.CharField(choices=[('CHECK_TARA_STATUS', 'Check Tara Status'), ('RETRY_CONFIRMATION', 'Retry Confirmation'), ('RETRY_PROVISIONING', 'Retry Provisioning'), ('CANCEL_ORDER', 'Cancel Order'), ('CANCEL_INSTALLMENT', 'Cancel Installment'), ('WAIVE_INSTALLMENT', 'Waive Installment'), ('APPLY_MANUAL_DISPOSITION', 'Apply Manual Disposition'), ('FREEZE_ENROLLMENT', 'Freeze Enrollment'), ('RESUME_ENROLLMENT', 'Resume Enrollment')], db_index=True, max_length=40),
        ),
    ]
