# Generated by Django 6.0.7 on 2026-08-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0014_alter_order_options_alter_adminauditlog_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminauditlog',
            name='target_type',
            field=models.CharField(choices=[('ORDER', 'Order'), ('INSTALLMENT', 'Installment'), ('PAYMENT_ATTEMPT', 'PaymentAttempt'), ('PAYMENT_CONFIRMATION', 'PaymentConfirmation'), ('PROVISIONING_REQUEST', 'ProvisioningRequest'), ('ENROLLMENT_ATTEMPT', 'EnrollmentAttempt')], db_index=True, max_length=30),
        ),
    ]
