# Generated by Django 6.1.1 on 2026-09-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0017_webhookevent_amount_and_attribution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarawebhookevent',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('', '—'), ('BUSINESS_ID_MISMATCH', 'businessId mismatch'), ('UNKNOWN_PRODUCT_ID', 'Unknown productId'), ('UNCORRELATED', 'No safe correlation available'), ('AMOUNT_MISMATCH', 'Webhook amount does not match the expected installment amount'), ('PAYMENT_ID_CONFLICT', 'Tara paymentId already linked to a different attempt'), ('DUPLICATE_PAYMENT', 'Verified payment for an installment already paid via another attempt'), ('INVALID_STATE_TRANSITION', 'Verified payment could not be applied in the current state'), ('PROVIDER_LOOKUP_INDETERMINATE', 'Server-to-server status lookup was indeterminate'), ('MALFORMED', 'Malformed or inconsistent provider response')], default='', max_length=40),
        ),
    ]
