# Generated by Django 6.1.1 on 2026-09-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0007_alter_course_slug_unique'),
        ('payments', '0019_webhook_failure_category_product_mismatch'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='order_status_valid',
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='orders_expired',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACTIVE', 'Active'), ('PAST_DUE', 'Past Due'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('SUSPENDED', 'Suspended'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'ACTIVE', 'PAST_DUE', 'COMPLETED', 'CANCELLED', 'SUSPENDED', 'EXPIRED'])), name='order_status_valid'),
        ),
    ]
