# Generated by Django 6.1.1 on 2026-09-25 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0020_order_expired_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='suspended_for_nonpayment_at',
            field=models.DateTimeField(blank=True, help_text='Set when access was suspended automatically because an installment stayed unpaid (InstallmentCollectionService). Only such suspensions are lifted automatically on payment — a manual suspension never is.', null=True),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='accesses_resumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='accesses_suspended',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reconciliationrun',
            name='installment_reminders_sent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='InstallmentReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('BEFORE_DUE', "Rappel avant l'échéance"), ('DUE_DAY', "Rappel le jour de l'échéance"), ('SUSPENDED', 'Accès suspendu pour impayé')], max_length=20)),
                ('status', models.CharField(choices=[('SENT', 'Envoyé'), ('FAILED', "Échec d'envoi"), ('SKIPPED_NO_EMAIL', "Pas d'adresse e-mail")], max_length=20)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='payments.installment')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('installment', 'kind'), name='one_reminder_per_installment_and_kind')],
            },
        ),
    ]
