# Generated by Django 6.0.6 on 2026-07-07 11:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0002_alter_course_workspace_id'),
        ('enrollments', '0002_alter_enrollmentattempt_cf_enrollment_id_and_more'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('provisioning_policy', models.CharField(choices=[('AUTOMATIC', 'Automatic'), ('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled (nightly batch)'), ('APPROVAL_REQUIRED', 'Approval required')], default='MANUAL', max_length=30)),
                ('expected_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Reference amount used only as a weak corroborating signal during payment matching — never sufficient on its own to trigger provisioning.', max_digits=12, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('courses', models.ManyToManyField(blank=True, related_name='products', to='courses.course')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_snapshot', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('attempt_count', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='contacts.contact')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='payments.payment')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='provisioning.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProvisioningAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILURE', 'Failure')], max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.course')),
                ('enrollment_attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='enrollments.enrollmentattempt')),
                ('provisioning_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='provisioning.provisioningrequest')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='tara', max_length=50)),
                ('external_ref', models.CharField(help_text="The exact product/reference identifier as sent by the provider (e.g. Tara's product/plan reference) — copy this verbatim from an unresolved Payment's product_ref, not a display name.", max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='provisioning.product')),
            ],
            options={
                'ordering': ['provider', 'external_ref'],
                'unique_together': {('provider', 'external_ref')},
            },
        ),
        migrations.AddIndex(
            model_name='provisioningrequest',
            index=models.Index(fields=['status', 'created_at'], name='provisionin_status_56f87c_idx'),
        ),
    ]
