# Generated by Django 6.0.5 on 2026-07-31 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0002_alter_course_workspace_id'),
        ('payments', '0009_paymentconfirmation'),
        ('provisioning', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningrequest',
            name='course',
            field=models.ForeignKey(blank=True, help_text="New-flow origin (Phase 7) only — the single course to enroll, from the Order's frozen snapshot.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='courses.course'),
        ),
        migrations.AddField(
            model_name='provisioningrequest',
            name='failure_category',
            field=models.CharField(blank=True, choices=[('', '—'), ('TRANSIENT_PROVIDER_ERROR', 'Transient provider error (timeout/5xx/rate limit)'), ('MISSING_CONTACT_IDENTIFIER', 'Missing contact email/identifier'), ('MISSING_COURSE_SNAPSHOT', 'Missing course_cf_id snapshot'), ('CONFIGURATION_ERROR', 'Invalid local configuration'), ('AUTHORIZATION_ERROR', 'Authorization failure requiring admin action'), ('MALFORMED_REQUEST', 'Malformed permanent request'), ('MAX_ATTEMPTS_EXCEEDED', 'Maximum attempts exceeded')], default='', max_length=40),
        ),
        migrations.AddField(
            model_name='provisioningrequest',
            name='order',
            field=models.ForeignKey(blank=True, help_text='New-flow origin (Phase 7) — audit link only. Never read for course/policy identity; course below is authoritative.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='payments.payment'),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='provisioning.product'),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='provisioningrequest',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('payment__isnull', False), ('product__isnull', False), ('order__isnull', True), ('course__isnull', True)), models.Q(('payment__isnull', True), ('product__isnull', True), ('order__isnull', False), ('course__isnull', False)), _connector='OR'), name='provisioning_request_exactly_one_origin'),
        ),
        migrations.AddConstraint(
            model_name='provisioningrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False), models.Q(('status', 'CANCELLED'), _negated=True)), fields=('contact', 'course'), name='unique_active_contact_course_provisioning_request'),
        ),
    ]
