# Generated by Django 6.0.5 on 2026-07-31 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0002_provisioningrequest_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provisioningrequest',
            options={'ordering': ['-created_at'], 'permissions': [('retry_provisioning_request', 'Can retry a FAILED or MANUAL_REVIEW provisioning request (Phase 8)')]},
        ),
    ]
