# Generated by Django 6.0.7 on 2026-08-04 19:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('courses', '0002_alter_course_workspace_id'),
        ('payments', '0012_remove_payment_payments_pa_status_343680_idx_and_more'),
        ('provisioning', '0003_alter_provisioningrequest_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='courses',
        ),
        migrations.RemoveField(
            model_name='productmapping',
            name='product',
        ),
        migrations.AlterUniqueTogether(
            name='productmapping',
            unique_together=None,
        ),
        migrations.RemoveConstraint(
            model_name='provisioningrequest',
            name='provisioning_request_exactly_one_origin',
        ),
        migrations.RemoveConstraint(
            model_name='provisioningrequest',
            name='unique_active_contact_course_provisioning_request',
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='course',
            field=models.ForeignKey(help_text="The single course to enroll, from the Order's frozen snapshot.", on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='courses.course'),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='order',
            field=models.ForeignKey(help_text='Audit link only. Never read for course/policy identity; course below is authoritative.', on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_requests', to='payments.order'),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='policy_snapshot',
            field=models.CharField(choices=[('AUTOMATIC', 'Automatic')], max_length=30),
        ),
        migrations.AlterField(
            model_name='provisioningrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('AWAITING_APPROVAL', 'Awaiting Approval'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('MANUAL_REVIEW', 'Manual Review'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='provisioningrequest',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'CANCELLED'), _negated=True), fields=('contact', 'course'), name='unique_active_contact_course_provisioning_request'),
        ),
        migrations.DeleteModel(
            name='ProductMapping',
        ),
        migrations.RemoveField(
            model_name='provisioningrequest',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='provisioningrequest',
            name='product',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
