# Generated by Django 6.0.7 on 2026-08-04 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0004_remove_product_courses_remove_productmapping_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisioningrequest',
            name='cf_suspended',
            field=models.BooleanField(default=False, help_text='Whether ClickFunnels access is currently suspended. Independent of `status`, which tracks provisioning-workflow success/failure, not live-access state — a COMPLETED request stays COMPLETED while suspended.'),
        ),
        migrations.AddField(
            model_name='provisioningrequest',
            name='cf_suspended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='provisioningrequest',
            name='cf_suspension_reason',
            field=models.TextField(blank=True),
        ),
    ]
