# Generated by Django 6.0.7 on 2026-08-04 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provisioning', '0005_provisioningrequest_cf_suspended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provisioningrequest',
            name='cf_suspended',
        ),
        migrations.RemoveField(
            model_name='provisioningrequest',
            name='cf_suspended_at',
        ),
        migrations.RemoveField(
            model_name='provisioningrequest',
            name='cf_suspension_reason',
        ),
    ]
